# this Makefile was generated automaticly by generic-makefile

.PHONY : run
run : ./output/bin.out
	time "./output/bin.out" hi!

./output/bin.out : banner  ./src/main.cpp ./extralib/fgh
./extralib/asd ./tmp/libproject.a


#    __
# __( o)>
# \ <_ ) r90
